# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    packSrc: "resource/i18n,manifest" # 需要打包资源目录。打包前manifest目录下的配置文件需改成正式环境
    arch: "amd64"
    system: "linux"
    version:  "v1.0.3"
    output:   "./bin"
    # output: "../main"
  gen:
    dao:
      - link: "mysql:web_apple_db:3Nmz5jprSdKLZDia@tcp(47.111.166.24:3306)/web_apple_db"
        group: "default"
        removePrefix: "apple_"
        daoPath: "dao/apple"
        doPath: "model/do/apple"
        entityPath: "model/entity/apple"
        tables: "apple_account"
        tplDaoIndexPath: "resource/gen/gen_dao_template_dao.txt"
        tplDaoInternalPath: "resource/gen/gen_dao_template_dao_internal.txt"
        overwriteDao: false
    pbentity:
#      - link: "mysql:root:Hym123456@tcp(0.0.0.0:3306)/web_apple_db"
#        tables: "auth_test"
