# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    packSrc: "manifest,resource" # 需要打包资源目录
    arch: "amd64"
    system: "linux"
    version: "v1.0.0"
    output: "./bin"
    # output: "../" #默认文件名main，也可写成../xxxx指定文件名
  gen:
    dao:
      - link: "mysql:ai_news:PHBrs6rpRwMC7Hz7@tcp(124.220.48.159:3306)/ai_news"
        group: "default"
        removePrefix: "ai_"
        daoPath: "dao/image"
        doPath: "model/do/image"
        entityPath: "model/entity/image"
        tables: "ai_image"
        tplDaoIndexPath: "resource/gen/gen_dao_template_dao.txt"
        tplDaoInternalPath: "resource/gen/gen_dao_template_dao_internal.txt"
        overwriteDao: true
    pbentity:
      - link: "mysql:ai_news:PHBrs6rpRwMC7Hz7@tcp(124.220.48.159:3306)/ai_news"
        tables: "auth_test"
