# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    packSrc: "resource/i18n,manifest" # 需要打包资源目录。打包前manifest目录下的配置文件需改成正式环境
    arch: "amd64"
    system: "linux"
    version: "v1.0.0"
    output: "./bin"
    # output: "../main"
  gen:
    dao:
      - link: "mysql:web_card_db:5ZKejwsiwhnT8sRG@tcp(47.111.166.24:3306)/web_card_db"
        group: "default"
        removePrefix: "app_"
        daoPath: "dao/app"
        doPath: "model/do/app"
        entityPath: "model/entity/app"
        tables: "app_card_countries"
        tplDaoIndexPath: "resource/gen/gen_dao_template_dao.txt"
        tplDaoInternalPath: "resource/gen/gen_dao_template_dao_internal.txt"
        overwriteDao: true
    pbentity:
      - link: "mysql:root:123456@tcp(0.0.0.0:3306)/dev_admin"
        tables: "auth_test"
