# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    packSrc: "resource/i18n,manifest" # 需要打包资源目录。打包前manifest目录下的配置文件需改成正式环境
    # output: "../main"
  gen:
    dao:
      - link: "mysql:root:Hym123456@tcp(0.0.0.0:3306)/web_video"
        group: "default"
        removePrefix: "web_"
        daoPath: "dao/movie"
        doPath: "model/do/movie"
        entityPath: "model/entity/movie"
        tables: "web_movie"
        tplDaoIndexPath: "resource/gen/gen_dao_template_dao.txt"
        tplDaoInternalPath: "resource/gen/gen_dao_template_dao_internal.txt"
        overwriteDao: false
    pbentity:
      - link: "mysql:root:Hym123456@tcp(0.0.0.0:3306)/web_video"
        tables: "auth_test"
